################################################################################
# SqlServer Imagem Alternativa - apenas redundancia do repo oficial
################################################################################

FROM liaisonintl/mssql-server-linux